### ISSUE TITLE
Release 4.28

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1087]
Umbrella bug to track release activities for 4.28
- [x] [New & Noteworthy](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1095)
- [x] [Readme file for 4.28](https://github.com/eclipse-platform/eclipse.platform.releng/issues/233) 
- [x] [Acknowledgment for 4.28](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1088) 
- [x] Tips & Tricks 
- [x] [Migration Guide](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1111)
- [x] [SWT Javadoc bash for 4.28](https://github.com/eclipse-platform/eclipse.platform.swt/issues/686)
- [x] [Publish to Maven central](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1134)
- [x] Tag Eclipse 4.28 Release 
- [x] Contribute to SimRel 
- [x] [Clean up intermediate artifacts (milestones, I-builds and old releases)](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1150)

Notification : @MohananRahul @deepika-u @alshamams @elsazac @subyssurendran666 @noopur2507 @mpalat @jarthana @Shee43

**Comment by deepika-u** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/issues/686

**Comment by Shee43** [comment]
https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/36 and https://github.com/eclipse-platform/eclipse.platform.releng/pull/234  for creating Readme files

Done on below environment:
Eclipse Platform
Version: 2023-06 (4.28)
Build id: I20230528-1800
OS: Mac OS X, v.13.3.1, aarch64 / cocoa
Java vendor: Oracle Corporation
Java runtime version: 19.0.2+7-44
Java version: 19.0.2

**Comment by noopur2507** [comment]
No new T&T to be added for 4.28.

**Comment by alshamams** [comment]
https://github.com/eclipse-platform/eclipse.platform.common/pull/148 


Done on below environment:
Eclipse Platform
Version: 2023-06 (4.28)
Build id: I20230528-1800
OS: Mac OS X, v.13.3.1, aarch64 / cocoa
Java vendor: Oracle Corporation
Java runtime version: 19.0.1+10-21
Java version: 19.0.1

**Comment by elsazac** [comment]
Publish to maven central is completed.

https://github.com/eclipse-platform/eclipse.platform.releng/pull/238
https://github.com/eclipse-platform/eclipse.platform.releng/pull/241

**Comment by MohananRahul** [comment]
Thanks @merks
