### ISSUE TITLE
Migration of website repos

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#182]
We are still waiting for a publishing solution by pulling php files from github repository. We already migrated couple of repositories. but their gerrit counterparts had to be used as intermediatery repositories as the publishing solution using github repositories is not yet available. 

Lets split migration of website repositories from code repositories and track them in this

- [x] #168 
- [x] [www.eclipse.org/equinox.git](https://github.com/eclipse-equinox/.github/issues/1)
- [x] [www.eclipse.org/jdt.git](https://github.com/eclipse-jdt/.github/issues/1)
- [x] [www.eclipse.org/pde.git](https://github.com/eclipse-pde/.github/issues/1)
- [x] #233

**Comment by niraj-modi** [comment]
Created below github issue on Eclipse foundation help-desk:
[Migrate www.eclipse.org/swt project to GitHub](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1198)

**Comment by fredg02** [comment]
Website content will no longer need to be copied from the GitHub repo to the Gerrit www repo.

Please see:
* [Project website repository move for equinox](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1792)
* [Project website repository move for jdt](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1811)
* [Project website repository move for pde](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1857)

For Platform and SWT, please wait for @eclipsewebmaster to confirm.

**Comment by akurtakov** [comment]
Closing this one as all subtasks are completed now.
