### ISSUE TITLE
Tracking I Build test results - 4.34 Version

### ISSUE THREAD

**Issue by mpalat** [eclipse-platform/eclipse.platform.releng.aggregator#2454]
Based on @akurtakov 's  mail - Refer: https://www.eclipse.org/lists/jdt-dev/msg02441.html

Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

Hoping to make this issue as a tracker for aiding the tracking of I Build failures. Let's have each of the components to have an issue listed here for daily tracking of I build test results:

 

- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3076
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1715
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/536

Additional Efforts for automation:

- [ ] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2451

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
4.34 is done now
