### ISSUE TITLE
Release 4.34

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#2532]
4.34 Release Task & GA
Umbrella bug to track release activities for 4.34

- [x] eclipse-platform/eclipse.platform.releng.aggregator#2533
- [x] eclipse-platform/www.eclipse.org-eclipse#248
- [x] Acknowledgment for 4.34
- [x] Tips & Tricks 
- [x] Migration Guide
- [x] [SWT Javadoc bash for 4.34](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1589)
- [x] #2606
- [x] Tag Eclipse 4.34 Release 
- [x] Contribute to SimRel 
- [x] Clean up intermediate artifacts (milestones, I-builds and old releases)

Notification : @deepika-u @elsazac @subyssurendran666 @noopur2507 @mpalat @jarthana @SougandhS

**Comment by deepika-u** [comment]
SWT task is being done in https://github.com/eclipse-platform/eclipse.platform.swt/issues/1589

**Comment by subyssurendran666** [comment]
The migration guide is tracked under https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2544

**Comment by noopur2507** [comment]
Tips and tricks tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2546.

**Comment by elsazac** [comment]
New and Noteworthy - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2533

**Comment by MohananRahul** [comment]
Promoted and Release
