### ISSUE TITLE
Preparation work for 4.35(2025-03) and open master for development

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#2550]
This preparation work involves the following tasks. For previous issue please refer to eclipse-platform/eclipse.platform.releng.aggregator#2274

- [x] eclipse-platform/eclipse.platform.releng.aggregator#2554
- [x] eclipse-platform/eclipse.platform.releng.aggregator#2556
- [x] eclipse-platform/eclipse.platform.releng.aggregator#2557
- [x] eclipse-platform/eclipse.platform.releng.aggregator#2559
- [x] eclipse-platform/eclipse.platform.releng.aggregator#2562
- [x] eclipse-platform/eclipse.platform#1634
- [x] #2564
- [x] #2567
- [x] #2568
- [x] Move previous version to 4.34RC2 across build scripts
- [x] #2577
- [x] #2580
- [x] eclipse-platform/eclipse.platform.releng.aggregator#2555
- [x] #2578
- [x] Create new I-build job for 4.35 release
- [x] #2586
- [x] #2588
- [x] Version bumps for 4.35 stream  Clean in https://download.eclipse.org/eclipse/downloads/drops4/I20241126-0110/buildlogs/reporeports/reports/versionChecks.html
- [x] #2607
- [x] Update build calendar for platform 4.35 release
- [x] Deploy ecj compiler from 4.34 GA and use it for 4.35 M1 build
- [x] Update generic repos I-builds, Y-builds, P-builds to point to 4.35 repos

**Comment by HannesWell** [comment]
> * Move previous version to 4.34RC2 across build scripts

@MohananRahul or @akurtakov can you tell if it would be possible to perform this step before creating all the version updated?
I.e. could we set the api- and comparator-baseline repo property `previous-release.baseline` to the current RC2-repo before the version updates are triggered, IIRC by creating the milestones? Then the workflows that perform the POM parent version updates could also immediately perform the version updates necessary in the bundle/feature projects because the project is changed the first time in a dev-cycle. See also https://github.com/eclipse-pde/eclipse.pde/pull/1489#issuecomment-2494993698

Maybe this should also be included in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2565?
Which makes me wonder if the `prepareRelease` workflow should be triggered on [`workflow_dispatch`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch), i.e. be executed manually. Then we could pass the next release as an input-argument plus the current RC2-repo to be used as baseline:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/63b98fe742f9c448a4fe33ab39ab8054ca93359b/.github/workflows/prepareRelease.yml#L2-L4

If that is the executed before the milestones are created all update-release workflows should then be able to succeed immediately, currently they are missing the parent-version in the repo because the PR mentioned above is currently also only created on milestone-creation too. And the workflow should be able to perform the necessary version bumps too.

@laeubi what do you think think?

**Comment by HannesWell** [comment]
Btw. if you set the `previous-release.baseline` now it would still be possible to avoid manual version bumps by simply re-running the `check-versions / Check and increment service versions` workflow in all `Update for release 4.35` PRs like https://github.com/eclipse-pde/eclipse.pde/pull/1489.
IIRC currently the process is to await the first I-build and fix the comparator-errors manually afterwards?

**Comment by HannesWell** [comment]
> Then we could pass the next release as an input-argument plus the current RC2-repo to be used as baseline:

At least the next version could also be computed by simply bumping the minor 'branding' version by one.
For the RC2 repo I currently have no smart way to compute it, except for looking it up in the SimRel contribution:
https://github.com/eclipse-simrel/simrel.build/blob/965a38026d3d81ae7a3ffe2957507a3d72af2698/ep.aggrcon#L3

**Comment by laeubi** [comment]
The prepare workflow is required to make the parent-pom available in the snapshot repository, the creation pf the PR triggers the deployment already so it can be used by other workflows a few seconds later.

Regarding the repositories, I already have suggested that we have ones with "stable" names so we can simply let this repo then point to whatever is required when (instead of changing the names all the time), e.g. currently the "new" comparator Ibuild repo is empty, and so we retain the previous one until the first successful ibuild then. Intead the "new" one could simply be a link to the "old" and will automatically be replaced by a new (successful) ibuild then.

Also the new 2024-12 could point to the 2024-12-RC2 unless there is a release so it could be used already before as a reference repository.

**Comment by HannesWell** [comment]
> The prepare workflow is required to make the parent-pom available in the snapshot repository, the creation pf the PR triggers the deployment already so it can be used by other workflows a few seconds later.

Now that you say it, I remember that, it's because of 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/63b98fe742f9c448a4fe33ab39ab8054ca93359b/Jenkinsfile#L26

I don't recalls exactly how milestones are created. I assumed it was in a Jenkins-job were they are all created at once? And then even these few seconds could have been too late to resolve the new parent-pom, if all the jobs start at the same time in all repos.
But if they are all created manually and subsequently, then it should be fine.

While writing this and after some search I found a `create-milestones` job being mentioned in the release process. But from the doc, I have the impression it's hidden, so I cannot tell what it does exactly.

**Comment by akurtakov** [comment]
All tasks done.
