### ISSUE TITLE
Release 4.24

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#273]
Umbrella bug to track release activities for 4.24

- [x] What's New - https://github.com/eclipse-platform/eclipse.platform.common/issues/21
- [x] eclipse-platform/www.eclipse.org-eclipse#7
- [x] eclipse-platform/www.eclipse.org-eclipse#6
- [x] Tips & Tricks
           1.  https://github.com/eclipse-pde/eclipse.pde/issues/131 (PDE tips and tricks)
           2. https://github.com/eclipse-jdt/eclipse.jdt/issues/17 (JDT tips and tricks)
           3. https://github.com/eclipse-platform/eclipse.platform/issues/20 (Platform tips and tricks)
- [x] Migration Guide (@ktatavarthi) 
           1. [Stub out 4.24 migration docs](https://git.eclipse.org/c/platform/eclipse.platform.common.git/commit/?id=4c65efd65bbc6610bb38a61ec951347e93b2c2a7)
           2. https://github.com/eclipse-jdt/eclipse.jdt/issues/15
           3. https://github.com/eclipse-platform/eclipse.platform/issues/16
- [x] eclipse-platform/eclipse.platform.swt#162
- [x] eclipse-platform/eclipse.platform.releng#45
- [x] eclipse-platform/eclipse.platform.releng.aggregator#343
- [x] #348
- [x] eclipse-platform/eclipse.platform.releng.aggregator#301 
- [x] eclipse-platform/eclipse.platform.releng.aggregator#334

@notifications:
@SarikaSinha, @lshanmug, @vik-chand, @ktatavarthi, @niraj-modi, @SDawley

**Comment by sravanlakkimsetti** [comment]
4.24 has been release
