### ISSUE TITLE
Preparation work for 4.25 (2022-09) and open master for development

### ISSUE THREAD

**Issue by SDawley** [eclipse-platform/eclipse.platform.releng.aggregator#284]
This preparation work involves the following tasks. For previous bug please refer to eclipse-platform/eclipse.platform.releng.aggregator#48 - Prep work for 4.24 (2022-03) and open master for development.

- [x] eclipse-platform/eclipse.platform.releng.aggregator#301
- [x] #317
- [x] eclipse-platform/eclipse.platform.releng.aggregator#286
- [x] eclipse-platform/eclipse.platform.releng.aggregator#287
- [x] eclipse-platform/eclipse.platform.swt#187
- [x] eclipse-platform/eclipse.platform#22
- [x] eclipse-platform/eclipse.platform.releng.aggregator#288
- [x] eclipse-platform/eclipse.platform.releng.aggregator#290
- [x] eclipse-platform/eclipse.platform.releng.aggregator#291
- [x] eclipse-platform/eclipse.platform.releng.aggregator#302
- [x] eclipse-platform/eclipse.platform.releng.aggregator#303
- [x] eclipse-platform/eclipse.platform.releng.aggregator#300
- [x] eclipse-platform/eclipse.platform.common#32
- [x] eclipse-platform/eclipse.platform.releng.aggregator#294
- [ ] https://github.com/eclipse-platform/www.eclipse.org-eclipse/issues/9
- [x] #305
- [x] #308
- [x] eclipse-platform/eclipse.platform.releng.aggregator#299
- [x] eclipse-platform/eclipse.platform.releng.aggregator#298
- [x] #313
- [x] #324
- [x] #333
- [x] eclipse-platform/eclipse.platform.releng.aggregator#289
- [x] #337
- [x] #319
