### ISSUE TITLE
Preparation work for 4.24 (2022-06) and open master for development

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#48]
This preparation work involves the following tasks. For previous bug please refer to [Bug 577436](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577436) - Prep work for 4.23 (2022-03) and open master for development

- [x] eclipse-platform/eclipse.platform.releng.aggregator#52
- [x] eclipse-platform/eclipse.platform.releng.aggregator#54
- [x] eclipse-platform/eclipse.platform.releng.aggregator#57
- [x] eclipse-platform/eclipse.platform.releng.aggregator#59
- [x] eclipse-platform/eclipse.platform.releng.aggregator#51
- [x] eclipse-platform/eclipse.platform.releng.aggregator#67
- [x] eclipse-platform/eclipse.platform.releng.aggregator#68
- [x] eclipse-platform/eclipse.platform.releng.aggregator#58
- [x] eclipse-platform/eclipse.platform.releng.aggregator#81
- [x] eclipse-platform/eclipse.platform.releng.aggregator#61
- [x] eclipse-platform/eclipse.platform.releng.aggregator#66
- [x] eclipse-platform/eclipse.platform.releng.aggregator#62
- [x] eclipse-platform/eclipse.platform.releng.aggregator#63
- [x] eclipse-platform/eclipse.platform.releng.aggregator#64
- [x] eclipse-platform/eclipse.platform.releng.aggregator#72
- [x] eclipse-platform/eclipse.platform.releng.aggregator#73
- [x] eclipse-platform/eclipse.platform.releng.aggregator#65
- [x] eclipse-platform/eclipse.platform.releng.aggregator#75
- [x] eclipse-platform/eclipse.platform.releng.aggregator#78
- [x] #85
- [x] #93 
- [x] #113
- [x] #101
- [x] #107
- [x] #117
