### ISSUE TITLE
Preparation work for 4.28 (2023-06) and open master for development

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#912]
- [x] #927
- [x] #958
- [x] #933
- [x] #936
- [x] #939
- [x] eclipse-platform/eclipse.platform.swt#565
- [x] eclipse-platform/eclipse.platform#345
- [x] #932
- [x] eclipse-platform/eclipse.platform.releng.aggregator#916
- [x] eclipse-platform/eclipse.platform.releng.aggregator#921
- [x] #931
- [x] https://github.com/eclipse-equinox/equinox/issues/224
- [x] #940
- [x] eclipse-platform/eclipse.platform.common#117
- [x] #941
- [x] eclipse-platform/eclipse.platform.releng.aggregator#922
- [x] #938
- [x] eclipse-platform/eclipse.platform.releng.aggregator#923
- [x] #937
- [x] eclipse-platform/eclipse.platform.releng.aggregator#917
- [x] #957
- [x] eclipse-platform/eclipse.platform.releng.aggregator#915
- [x] #960
- [x] #959

For previous issue refer to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/496

**Comment by sravanlakkimsetti** [comment]
all the dependent tasks complete closing
